# Create a stage for processing configuration
FROM alpine as config-processor
RUN apk add --no-cache gettext
COPY src/main/resources/application.yml /tmp/
RUN envsubst < /tmp/application.yml > /tmp/application-processed.yml

From openjdk:21
EXPOSE 8080
RUN mkdir /app
COPY --from=config-processor /tmp/application-processed.yml /app/config/application.yml
COPY build/libs/*.jar /app/multi-signin.jar
ENTRYPOINT ["java","-jar","/app/multi-signin.jar"]