ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET

ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} \
    GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} \
From openjdk:21
EXPOSE 8080
RUN mkdir /app
COPY build/libs/*.jar /app/multi-signin.jar
ENTRYPOINT ["java","-jar","/app/multi-signin.jar"]